[project]
name = "cat-feeding-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "discord-py>=2.5.2",
  "mypy>=1.17.1",
  "pre-commit>=4.2.0",
  "python-dotenv>=1.1.1",
  "ruff>=0.12.7",
  "supabase>=2.17.0"
]
